name: Android

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: Set execute permission
        run: chmod +x ./mvnw

      - name: Gluon Build
        run: |
          export ANDROID_SDK=$ANDROID_HOME
          ./mvnw -Pandroid gluonfx:build gluonfx:package

      - name: Make staging directory
        run: mkdir staging

      - name: Copy packages to staging
        run: cp -r target/gluonfx/aarch64-android/gvm/CaiDanCi.* staging

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging