name: Windows

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v1

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make staging directory
        run: mkdir staging

      - name: Gluon Build and Package
        shell: cmd
        run: .\mvnw -Pdesktop gluonfx:build gluonfx:package

      - name: Copy native bundles to staging
        run: |
          cp -r target/gluonfx/x86_64-windows/CaiDanCi.exe staging
          cp -r target/gluonfx/x86_64-windows/CaiDanCi-1.0.msi staging

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
